CREATE TABLE TB_DIM_TEMPO (
    SK_DATA INTEGER NOT NULL,
    DATA DATE NOT NULL,
    NR_ANO INTEGER(4) NOT NULL,
    NR_MES INTEGER NOT NULL,
    NM_MES VARCHAR(20) NOT NULL,
    NR_DIA INTEGER NOT NULL,
    CONSTRAINT TB_DIM_DATA_PK PRIMARY KEY (SK_DATA) 
);


INSERT INTO TB_DIM_TEMPO
SELECT 
 DATE_FORMAT('2015-12-31' + INTERVAL n DAY,'%Y%m%d') AS SK_DATA,
 '2015-12-31' + INTERVAL n DAY AS Full_Date,
 DATE_FORMAT('2015-12-31' + INTERVAL n DAY,'%Y') AS NR_ANO,
 DATE_FORMAT('2015-12-31' + INTERVAL n DAY,'%m') AS NR_MES,
 DATE_FORMAT('2015-12-31' + INTERVAL n DAY,'%M') AS NM_MES,
 DATE_FORMAT('2015-12-31' + INTERVAL n DAY,'%d') AS NR_DIA
FROM (
 SELECT t1.n + t2.n * 10 + t3.n * 100 AS n
 FROM 
 (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS t1,
 (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS t2,
 (SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS t3
) AS numbers
WHERE n <= 2000;
COMMIT;

SELECT * FROM TB_DIM_TEMPO LIMIT 100;