
CREATE TABLE TB_DIM_CLIENTE 
(
  SK_CLIENTE INT AUTO_INCREMENT,
  NK_ID_CLIENTE VARCHAR(20), 
  NM_CLIENTE VARCHAR(50), 
  NM_CIDADE_CLIENTE VARCHAR(50), 
  FLAG_ACEITA_CAMPANHA CHAR(1), 
  DESC_CEP VARCHAR(10), 
  CONSTRAINT TB_DIM_CLIENTE_PK PRIMARY KEY (SK_CLIENTE) 
);
