ALTER TABLE TB_FATO_VENDA
ADD CONSTRAINT TB_FATO_VENDA_FK_CLIENTE FOREIGN KEY(
    SK_CLIENTE
) REFERENCES TB_DIM_CLIENTE(
    SK_CLIENTE
);

ALTER TABLE TB_FATO_VENDA
ADD CONSTRAINT TB_FATO_VENDA_FK_DATA FOREIGN KEY(
    SK_DATA
) REFERENCES TB_DIM_TEMPO(
    SK_DATA
);

ALTER TABLE TB_FATO_VENDA
ADD CONSTRAINT TB_FATO_VENDA_FK_LOC FOREIGN KEY(
    SK_LOCALIDADE
) REFERENCES TB_DIM_LOCALIDADE(
    SK_LOCALIDADE
);

ALTER TABLE TB_FATO_VENDA
ADD CONSTRAINT TB_FATO_VENDA_FK_PRODUTO FOREIGN KEY(
    SK_PRODUTO
) REFERENCES TB_DIM_PRODUTO(
    SK_PRODUTO
);