use dw;
INSERT INTO TB_DIM_CLIENTE ( NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, FLAG_ACEITA_CAMPANHA, DESC_CEP )
SELECT NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, FLAG_ACEITA_CAMPANHA, DESC_CEP
FROM starea.ST_DIM_CLIENTE;
COMMIT;

INSERT INTO TB_DIM_PRODUTO(NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO)
SELECT NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO
FROM starea.ST_DIM_PRODUTO;
COMMIT;

INSERT INTO TB_DIM_LOCALIDADE(NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE)
SELECT NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE
FROM starea.ST_DIM_LOCALIDADE;
COMMIT;


-- Carga de Dados
USE dw;
INSERT INTO TB_FATO_VENDA
SELECT B.SK_CLIENTE as SK_CLIENTE, 
       C.SK_PRODUTO as SK_PRODUTO, 
       D.SK_LOCALIDADE as SK_LOCALIDADE,
       CAST(DATE_FORMAT(DATA_VENDA, '%Y%m%d') AS UNSIGNED) AS SK_DATA,
       (A.PRECO_UNITARIO * A.QUANTIDADE) as VL_VENDA,
       A.QUANTIDADE as QTD_VENDA,
       CURRENT_DATE
FROM starea.ST_VENDA A, TB_DIM_CLIENTE B, TB_DIM_PRODUTO C, TB_DIM_LOCALIDADE D
WHERE A.ID_CLIENTE = B.NK_ID_CLIENTE
  AND A.ID_PRODUTO = C.NK_ID_PRODUTO
  AND A.ID_LOCALIDADE = D.NK_ID_LOCALIDADE;
COMMIT;

SELECT * FROM starea.ST_VENDA;

SELECT A.ID_TRANSACAO, B.SK_CLIENTE 
  FROM starea.ST_VENDA A, TB_DIM_CLIENTE B 
 WHERE A.ID_CLIENTE = B.NK_ID_CLIENTE;

SELECT A.ID_TRANSACAO, B.SK_CLIENTE 
  FROM starea.ST_VENDA A LEFT JOIN TB_DIM_CLIENTE B 
    ON A.ID_CLIENTE = B.NK_ID_CLIENTE;

INSERT INTO TB_DIM_CLIENTE VALUES(-1, -1, '<não identificado>', '<não identificado>', 0, 'NA');
COMMIT;

INSERT INTO TB_DIM_PRODUTO VALUES(-1, -1, '<não identificado>', '<não identificado>', '<não identificado>', '<não identificado>');
COMMIT;

INSERT INTO TB_DIM_LOCALIDADE VALUES(-1, -1, '<não identificado>', '<não identificado>', '<não identificado>');
COMMIT;

TRUNCATE TABLE TB_FATO_VENDA;

INSERT INTO TB_FATO_VENDA
SELECT coalesce(B.SK_CLIENTE, -1) as SK_CLIENTE, 
       coalesce(C.SK_PRODUTO, -1) as SK_PRODUTO, 
       coalesce(D.SK_LOCALIDADE, -1) as SK_LOCALIDADE,
       CAST(DATE_FORMAT(DATA_VENDA, '%Y%m%d') AS UNSIGNED) AS SK_DATA,
       (A.PRECO_UNITARIO * A.QUANTIDADE) as VL_VENDA,
       A.QUANTIDADE as QTD_VENDA,
       CURRENT_DATE
FROM starea.ST_VENDA A LEFT JOIN TB_DIM_CLIENTE B 
  ON A.ID_CLIENTE = B.NK_ID_CLIENTE
  LEFT JOIN TB_DIM_PRODUTO C 
  ON A.ID_PRODUTO = C.NK_ID_PRODUTO
  LEFT JOIN TB_DIM_LOCALIDADE D
  ON A.ID_LOCALIDADE = D.NK_ID_LOCALIDADE;
COMMIT;
