USE TBS_SOURCE;

CREATE TABLE TB_CADASTRO_CLIENTE 
(
  ID_CLIENTE INTEGER  NOT NULL 
, NOME_CLIENTE VARCHAR(100) 
, EMAIL_CLIENTE VARCHAR(50) 
, CONSTRAINT TB_CADASTRO_CLIENTE_PK PRIMARY KEY 
  (
    ID_CLIENTE 
  )

);

CREATE TABLE TB_ENDERECO 
(
  ID_ENDERECO INTEGER NOT NULL 
, LOGRADOURO VARCHAR(50) 
, NUMERO INTEGER 
, CIDADE VARCHAR(20) 
, ESTADO VARCHAR(20) 
, PAIS VARCHAR(20) 
, CEP VARCHAR(20) 
, ID_CLIENTE INTEGER
, CONSTRAINT TB_ENDERECO_PK PRIMARY KEY 
  (
    ID_ENDERECO 
  )
   
);

ALTER TABLE TB_ENDERECO
ADD CONSTRAINT TB_ENDERECO_FK1 FOREIGN KEY
(
  ID_CLIENTE 
)
REFERENCES TB_CADASTRO_CLIENTE
(
  ID_CLIENTE 
)
;
DROP TABLE TB_PEDIDOS;
CREATE TABLE TB_PEDIDOS 
(
  ID_TRANSACAO BIGINT NOT NULL 
, DATA_TRANSACAO TIMESTAMP 
, DATA_ENTREGA TIMESTAMP 
, STATUS_PAGAMENTO VARCHAR(20) 
, ID_CLIENTE INTEGER 
, ID_LOCALIDADE INTEGER 
, CONSTRAINT TB_PEDIDOS_PK PRIMARY KEY 
  (
    ID_TRANSACAO 
  )
   
);

CREATE TABLE TB_CATEGORIA 
(
  ID_CATEGORIA INTEGER NOT NULL 
, NOME_CATEGORIA VARCHAR(20) 
, NOME_SUB_CATEGORIA VARCHAR(20) 
, CONSTRAINT TB_CATEGORIA_PK PRIMARY KEY 
  (
    ID_CATEGORIA 
  )
   
);

ALTER TABLE TB_PRODUTO
ADD CONSTRAINT TB_PRODUTO_FK1 FOREIGN KEY
(
  ID_CATEGORIA 
)
REFERENCES TB_CATEGORIA
(
  ID_CATEGORIA 
)
;

CREATE TABLE TB_LOCALIDADE 
(
  ID_LOCALIDADE INTEGER NOT NULL 
, NOME_LOCALIDADE VARCHAR(100) 
, CIDADE_LOCALIDADE VARCHAR(20) 
, CONSTRAINT TB_LOCALIDADE_PK PRIMARY KEY 
  (
    ID_LOCALIDADE 
  )
   
);


CREATE TABLE TB_PEDIDOS 
(
  ID_TRANSACAO INTEGER NOT NULL 
, DATA_TRANSACAO TIMESTAMP 
, DATA_ENTREGA TIMESTAMP 
, STATUS_PAGAMENTO VARCHAR(20) 
, ID_CLIENTE INTEGER 
, ID_LOCALIDADE INTEGER 
, CONSTRAINT TB_PEDIDOS_PK PRIMARY KEY 
  (
    ID_TRANSACAO 
  )
   
);

ALTER TABLE TB_PEDIDOS
ADD CONSTRAINT TB_PEDIDOS_FK1 FOREIGN KEY
(
  ID_CLIENTE 
)
REFERENCES TB_CADASTRO_CLIENTE
(
  ID_CLIENTE 
)
;

ALTER TABLE TB_PEDIDOS
ADD CONSTRAINT TB_PEDIDOS_FK2 FOREIGN KEY
(
  ID_LOCALIDADE 
)
REFERENCES TB_LOCALIDADE
(
  ID_LOCALIDADE 
)
;




CREATE TABLE TB_ITENS_PEDIDO 
(
  ID_TRANSACAO BIGINT NOT NULL 
, ID_PRODUTO INTEGER NOT NULL 
, QUANTIDADE INTEGER 
, PRECO_UNITARIO DOUBLE PRECISION 
, CONSTRAINT TB_ITENS_PEDIDO_PK PRIMARY KEY 
  (
    ID_TRANSACAO 
  , ID_PRODUTO 
  )
   
);

ALTER TABLE TB_ITENS_PEDIDO
ADD CONSTRAINT TB_ITENS_PEDIDO_FK1 FOREIGN KEY
(
  ID_PRODUTO 
)
REFERENCES TB_PRODUTO
(
  ID_PRODUTO 
)
;