SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `DIM_CLIENT`;
DROP TABLE IF EXISTS `FACT_ORDER`;
DROP TABLE IF EXISTS `DIM_LOCATION`;
DROP TABLE IF EXISTS `DIM_TIME`;
DROP TABLE IF EXISTS `DIM_PRODUCT`;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `DIM_CLIENT` (
    `SK_CLIENT` INTEGER(20) NOT NULL,
    `NK_CLIENT` INTEGER(20) NOT NULL,
    `NAME_CLIENT` INTEGER(20) NOT NULL,
    `NAME_CLIENT_CITY` INTEGER(20) NOT NULL,
    `IS_MARKETING_CAMPAIGNS` BINARY NOT NULL,
    `DESC_CEP` CHAR(10) NOT NULL,
    PRIMARY KEY (`SK_CLIENT`)
);

CREATE TABLE `FACT_ORDER` (
    `SK_CLIENT` INTEGER(20) NOT NULL,
    `SK_PRODUCT` INTEGER(20) NOT NULL,
    `SK_LOCATION` INTEGER(20) NOT NULL,
    `SK_TIME` INTEGER(20) NOT NULL,
    `AMT_ORDER_PRICE` DECIMAL NOT NULL,
    `QTY_ORDER` INTEGER NOT NULL,
    PRIMARY KEY (`SK_CLIENT`, `SK_PRODUCT`, `SK_LOCATION`, `SK_TIME`)
);

CREATE TABLE `DIM_LOCATION` (
    `SK_LOCATION` INTEGER(20) NOT NULL,
    `NK_LOCATION` VARCHAR(20) NOT NULL,
    `NAME_LOCATION` VARCHAR(50) NOT NULL,
    `NAME_CITY_LOCATION` VARCHAR(50) NOT NULL,
    `NAME_REGION_LOCATION` VARCHAR(50) NOT NULL,
    `ORDER_QTY` INTEGER NOT NULL,
    PRIMARY KEY (`SK_LOCATION`)
);

CREATE TABLE `DIM_TIME` (
    `SK_DATE` INTEGER(20) NOT NULL,
    `DATE` DATE NOT NULL,
    `DESC_FULL_DATE` VARCHAR(50) NOT NULL,
    `NUM_YEAR` INTEGER(4) NOT NULL,
    `NUM_TRIMESTER` INTEGER(1) NOT NULL,
    `NUM_MONTH` INTEGER(1) NOT NULL,
    `NAME_MONTH` VARCHAR(20) NOT NULL,
    `NUM_WEEK` INTEGER NOT NULL,
    `NAME_YEAR_WEEK` VARCHAR(20) NOT NULL,
    `NUM_DAY` INTEGER NOT NULL,
    `NAME_DAY_WEEK` VARCHAR(20) NOT NULL,
    `IS_HOLIDAY` VARCHAR(3) NOT NULL,
    `NAME_HOLIDAY` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`SK_DATE`)
);

CREATE TABLE `DIM_PRODUCT` (
    `SK_PRODUCT` INTEGER(20) NOT NULL,
    `NK_PRODUCT` VARCHAR(20) NOT NULL,
    `DESC_PRODUCT` VARCHAR(50) NOT NULL,
    `DESC_PRODUCT` VARCHAR(50) NOT NULL,
    `NAME_CATEGORY_PRODUCT` VARCHAR(30) NOT NULL,
    `NAME_BRAND_PRODUCT` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`SK_PRODUCT`)
);
