--* Create tables as Stage area

USE starea;

CREATE TABLE ST_CADASTRO_CLIENTE 
(
  ID_CLIENTE INTEGER  NOT NULL 
, NOME_CLIENTE VARCHAR(255) 
, EMAIL_CLIENTE VARCHAR(255) 
);

CREATE TABLE ST_ENDERECO 
(
  ID_ENDERECO INTEGER NOT NULL 
, LOGRADOURO VARCHAR(255) 
, NUMERO INTEGER 
, CIDADE VARCHAR(2255) 
, ESTADO VARCHAR(255) 
, PAIS VARCHAR(255) 
, CEP VARCHAR(255) 
, ID_CLIENTE INTEGER
);


CREATE TABLE ST_PRODUTO 
(
  ID_PRODUTO INTEGER NOT NULL 
, SKU VARCHAR(255) 
, NOME_PRODUTO VARCHAR(255) 
, ID_CATEGORIA INTEGER
);

CREATE TABLE ST_CATEGORIA 
(
  ID_CATEGORIA INTEGER NOT NULL 
, NOME_CATEGORIA VARCHAR(255) 
, NOME_SUB_CATEGORIA VARCHAR(255) 
);

CREATE TABLE ST_LOCALIDADE 
(
  ID_LOCALIDADE INTEGER NOT NULL 
, NOME_LOCALIDADE VARCHAR(255) 
, CIDADE_LOCALIDADE VARCHAR(255) 
);


CREATE TABLE ST_PEDIDOS 
(
  ID_TRANSACAO INTEGER NOT NULL 
, DATA_TRANSACAO TIMESTAMP 
, DATA_ENTREGA TIMESTAMP 
, STATUS_PAGAMENTO VARCHAR(255) 
, ID_CLIENTE INTEGER 
, ID_LOCALIDADE INTEGER 
);


CREATE TABLE ST_ITENS_PEDIDO 
(
  ID_TRANSACAO INTEGER NOT NULL 
, ID_PRODUTO INTEGER NOT NULL 
, QUANTIDADE INTEGER 
, PRECO_UNITARIO DOUBLE PRECISION 
);