use dw;
INSERT INTO TB_DIM_CLIENTE ( NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, FLAG_ACEITA_CAMPANHA, DESC_CEP )
SELECT NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, FLAG_ACEITA_CAMPANHA, DESC_CEP
FROM starea.ST_DIM_CLIENTE;
COMMIT;

INSERT INTO TB_DIM_PRODUTO(NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO)
SELECT NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO
FROM starea.ST_DIM_PRODUTO;
COMMIT;

INSERT INTO TB_DIM_LOCALIDADE(NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE)
SELECT NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE
FROM starea.ST_DIM_LOCALIDADE;
COMMIT;
