CREATE TABLE TB_DIM_LOCALIDADE (
    SK_LOCALIDADE INTEGER AUTO_INCREMENT,
    NK_ID_LOCALIDADE VARCHAR(20) NOT NULL,
    NM_LOCALIDADE VARCHAR(50) NOT NULL,
    NM_CIDADE_LOCALIDADE VARCHAR(50) NOT NULL,
    NM_REGIAO_LOCALIDADE VARCHAR(50) NOT NULL,
    CONSTRAINT TB_DIM_LOCALIDADE_PK PRIMARY KEY (SK_LOCALIDADE) 
);