-- Active: 1716831872698@@192.168.64.7@3306
CREATE TABLE TB_DIM_PRODUTO (
    SK_PRODUTO INT AUTO_INCREMENT,
    NK_ID_PRODUTO VARCHAR(20) NOT NULL,
    DESC_SKU VARCHAR(50) NOT NULL,
    NM_PRODUTO VARCHAR(50) NOT NULL,
    NM_CATEGORIA_PRODUTO VARCHAR(30) NOT NULL,
    NM_MARCA_PRODUTO VARCHAR(30) NOT NULL,
    CONSTRAINT TB_DIM_PRODUTO_PK PRIMARY KEY (SK_PRODUTO) 
);

use dw;
SELECT * FROM `TB_DIM_PRODUTO`