USE starea;
DROP TABLE ST_DIM_PRODUTO;
CREATE TABLE ST_DIM_PRODUTO (
    NK_ID_PRODUTO VARCHAR(20) NOT NULL,
    DESC_SKU VARCHAR(50) NOT NULL,
    NM_PRODUTO VARCHAR(50) NOT NULL,
    NK_CATEGORIA_PRODUTO INTEGER NOT NULL,
    NM_CATEGORIA_PRODUTO VARCHAR(30) NOT NULL,
    NK_CATEGORIA_PAI INTEGER,
    NM_CATEGORIA_PAI VARCHAR(30),
    NM_MARCA_PRODUTO VARCHAR(30) NOT NULL
);


INSERT INTO ST_DIM_PRODUTO (
    NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NK_CATEGORIA_PRODUTO,
    NM_CATEGORIA_PRODUTO, NK_CATEGORIA_PAI, NM_CATEGORIA_PAI, NM_MARCA_PRODUTO
)
SELECT A.ID_PRODUTO, A.SKU, A.NOME_PRODUTO, B.ID_CATEGORIA, B.NOME_CATEGORIA, 
    B.ID_CATEGORIA_PAI, C.NOME_CATEGORIA,
CASE
    WHEN A.NOME_PRODUTO LIKE '%Sony%' THEN 'Sony'
    WHEN A.NOME_PRODUTO LIKE '%Iphone%' THEN 'Apple'
    WHEN A.NOME_PRODUTO LIKE '%MSI%' THEN 'MSI'
    WHEN A.NOME_PRODUTO LIKE '%Galaxy%' THEN 'Samsung'
    WHEN A.NOME_PRODUTO LIKE '%ASUS%' THEN 'Asus'
    WHEN A.NOME_PRODUTO LIKE '%Vaio%' THEN 'Vaio'
    WHEN A.NOME_PRODUTO LIKE '%Canon%' THEN 'Canon'
ELSE 'NA'
END as MARCA_PRODUTO
FROM st_tb_produto AS A, st_tb_categoria AS B, st_tb_categoria AS C
WHERE A.ID_CATEGORIA = B.ID_CATEGORIA AND 
    B.ID_CATEGORIA_PAI = C.ID_CATEGORIA;
COMMIT;

SELECT * FROM ST_DIM_PRODUTO