CREATE TABLE ST_DIM_LOCALIDADE (
    NK_ID_LOCALIDADE VARCHAR(20) NOT NULL,
    NM_LOCALIDADE VARCHAR(50) NOT NULL,
    NM_CIDADE_LOCALIDADE VARCHAR(50) NOT NULL,
    NM_REGIAO_LOCALIDADE VARCHAR(50) NOT NULL
);

INSERT INTO ST_DIM_LOCALIDADE
SELECT ID_LOCALIDADE, NOME_LOCALIDADE, CIDADE_LOCALIDADE,  
CASE
WHEN CIDADE_LOCALIDADE = 'Barueri' THEN 'Sudeste'
WHEN CIDADE_LOCALIDADE = 'São Paulo' THEN 'Sudeste'
WHEN CIDADE_LOCALIDADE = 'Rio de Janeiro' THEN 'Sudeste'
WHEN CIDADE_LOCALIDADE = 'Salvador' THEN 'Nordeste'
WHEN CIDADE_LOCALIDADE = 'Tatuapé' THEN 'Sudeste'
ELSE 'NA'
END as REGIAO
FROM st_tb_localidade;
COMMIT;