CREATE TABLE ST_DIM_PRODUTO (
    NK_ID_PRODUTO VARCHAR(20) NOT NULL,
    DESC_SKU VARCHAR(50) NOT NULL,
    NM_PRODUTO VARCHAR(50) NOT NULL,
    NM_CATEGORIA_PRODUTO VARCHAR(30) NOT NULL,
    NM_MARCA_PRODUTO VARCHAR(30) NOT NULL
);

SELECT A.ID_PRODUTO, A.SKU, A.NOME_PRODUTO, B.NOME_CATEGORIA
FROM st_tb_produto A, st_tb_categoria B
WHERE A.ID_CATEGORIA = B.ID_CATEGORIA;

INSERT INTO ST_DIM_PRODUTO
SELECT A.ID_PRODUTO, A.SKU, A.NOME_PRODUTO, B.NOME_CATEGORIA,
CASE
WHEN A.NOME_PRODUTO LIKE '%Sony%' THEN 'Sony'
WHEN A.NOME_PRODUTO LIKE '%Iphone%' THEN 'Apple'
WHEN A.NOME_PRODUTO LIKE '%MSI%' THEN 'MSI'
WHEN A.NOME_PRODUTO LIKE '%Galaxy%' THEN 'Samsung'
WHEN A.NOME_PRODUTO LIKE '%ASUS%' THEN 'Asus'
WHEN A.NOME_PRODUTO LIKE '%Vaio%' THEN 'Vaio'
WHEN A.NOME_PRODUTO LIKE '%Canon%' THEN 'Canon'
ELSE 'NA'
END as MARCA_PRODUTO
FROM st_tb_produto A, st_tb_categoria B
WHERE A.ID_CATEGORIA = B.ID_CATEGORIA;
COMMIT;


SELECT * FROM ST_DIM_PRODUTO